# -*- coding: utf-8 -*-
"""Python 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Gz7xWMe2neRgNE8y2FN8cM2fkIGnIRjm
"""

# Inisialisasi variabel untuk menyimpan panjang, lebar, dan tinggi
panjang = 20.5
lebar = 25
tinggi = 10

# Menghitung keliling
keliling = 2 * (panjang + lebar)

# Menghitung luas
luas = (panjang * lebar)

# Menghitung volume
volume = panjang * lebar * tinggi

# Mencetak hasil perhitungan ke layar
print('Panjang =', panjang)
print('Lebar =', lebar)
print('Tinggi =', tinggi)
print('Keliling =', keliling)
print('Luas =', luas)
print('Volume =', volume)

# Kamus data
mahasiswa = {
    'Shafira': [85, 75],
    'Amanda': [80, 90],
    'Aditya': [75, 80],
    'Nedia': [95, 80],
    'Widya': [85, 85],
    'Hanif': [75, 90],
    'Andi': [70, 75],
    'Dhanar': [85, 85],
    'Hikma': [80, 75]
}

# Fungsi untuk menghitung rata-rata nilai
def hitung_rata_rata(nilai):
    return sum(nilai) / len(nilai)

# 1. Rata-rata nilai Shafira pada kedua mata kuliah
rata_rata_shafira = hitung_rata_rata(mahasiswa["Shafira"])
print('Rata-rata nilai Shafira : ', rata_rata_shafira)

# 2. Jumlah nilai Hanif dan Andi untuk semua mata kuliah
jumlah_nilai_hanif_andi = sum(mahasiswa['Hanif']) + sum(mahasiswa['Andi'])
print('Jumlah nilai Hanif dan Andi : ', jumlah_nilai_hanif_andi)

# 3. Rata-rata nilai Widya, Dhanar, Hikma dan Nedia pada masing-masing mata kuliah
mahasiswa_terpilih = ['Widya', 'Dhanar', 'Hikma', 'Nedia']
jumlah_nilai_kalkulus = 0
jumlah_nilai_statistika = 0
for nama in mahasiswa_terpilih:
    jumlah_nilai_kalkulus += mahasiswa[nama][0]
    jumlah_nilai_statistika += mahasiswa[nama][1]
rata_rata_kalkulus = jumlah_nilai_kalkulus / len(mahasiswa_terpilih)
rata_rata_statistika = jumlah_nilai_statistika / len(mahasiswa_terpilih)
print('Rata-rata nilai Kalkulus untuk Widya, Dhanar, Hikma, dan Nedia :', rata_rata_kalkulus)
print('Rata-rata nilai Statistika untuk Widya, Dhanar, Hikma, dan Nedia :', rata_rata_statistika)

# 4. Rata-rata nilai mata kuliah Kalkulus 1 untuk semua mahasiswa
jumlah_nilai_kalkulus_semua = sum([nilai[0] for nilai in mahasiswa.values()])
rata_rata_kalkulus_semua = jumlah_nilai_kalkulus_semua / len(mahasiswa)
print('Rata-rata nilai Kalkulus 1 untuk semua mahasiswa :', rata_rata_kalkulus_semua)

# 5. Rata-rata nilai mata kuliah Metode Statistika untuk semua mahasiswa
jumlah_nilai_statistika_semua = sum([nilai[1] for nilai in mahasiswa.values()])
rata_rata_statistika_semua = jumlah_nilai_statistika_semua / len(mahasiswa)
print('Rata-rata nilai Metode Statistika untuk semua mahasiswa :', rata_rata_statistika_semua)

print("")

# Jumlah hari kerja dalam bulan Agustus (asumsi 31 hari)
hari_kerja_sebulan = 31

# Gaji pokok per jam
gaji_pokok_per_jam = 30000

# Jam kerja per hari
jam_kerja_per_hari = 8

# Tunjangan untuk karyawan yang bekerja lebih dari 5 tahun
tunjangan_5_tahun = 0.10  # 10%

# Gaji lembur per jam
gaji_lembur_per_jam = 10000

# Hari kerja Dwi di bulan Agustus
hari_kerja_dwi = hari_kerja_sebulan - 3  # Tidak masuk kerja selama 3 hari

# 1. Gaji Dwi di bulan Agustus
total_jam_kerja = hari_kerja_dwi * jam_kerja_per_hari
gaji_dwi = total_jam_kerja * gaji_pokok_per_jam
print("Gaji Dwi pada bulan Agustus:", gaji_dwi)

# 2. Tunjangan Dwi
tunjangan = gaji_dwi * tunjangan_5_tahun
print("Tunjangan Dwi pada bulan Agustus:", tunjangan)

# 3. Gaji total Dwi dengan lembur
jam_lembur = 5
gaji_lembur = jam_lembur * gaji_lembur_per_jam
gaji_total_dwi = gaji_dwi + tunjangan + gaji_lembur
print("Gaji total Dwi pada bulan Agustus dengan lembur:", gaji_total_dwi)